[package]
name = "hermes"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2.2.4"
tokio = { version = "1.41.0", features = ["rt", "sync"] }
tracing = "0.1.40"
uuid = { version = "1.11.0", features = ["v4"] }
